---

stages:
  - build
  - pack
  # - deploy

job_jekyll_build:
  stage: build
  image: docker-registry.data.bas.ac.uk/bsk/bas-style-kit-docs:alpine
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

job_pack_artifact:
  stage: pack
  image: antarctica/jekyll-deployment-image:alpine-gitlab-0.1.3
  before_script:
    - "export CI_BUILD_REF_SHORT=`echo $CI_BUILD_REF | cut -c1-7`"
    - "export DATETIME_INSTANT=`date --utc -I=seconds`"
  script:
    - "ls"
    - "ls site"
    - "ls /cache"
    - "echo $CI_PROJECT_DIR/$CI_BUILD_REF_SHORT-content-$DATETIME_INSTANT"
# Note: GitLab automatically passes artifacts from previous stages by default.

# job_s3_deploy_staging:
#   stage: deploy
#   image: antarctica/jekyll-deployment-image
#   only: develop
#   variables:
#     - S3_DEPLOYMENT_BUCKET: style-kit-testing.web.bas.ac.uk
#   environment:
#     name: staging (testing)
#     url: https://style-kit-testing.web.bas.ac.uk

# job_s3_deploy_production:
#   stage: deploy
#   image: antarctica/jekyll-deployment-image
#   only: master
#   variables:
#     - S3_DEPLOYMENT_BUCKET: style-kit.web.bas.ac.uk
#   environment:
#     name: production
#     url: https://style-kit.web.bas.ac.uk
