---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This configuration file uses some advanced YAML features (namely anchors) which may not be correctly displayed
#   by syntax highlighting
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs/settings/ci_cd -
#   see below

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensetive values are represented by "[Sensetive]"
#
# - AWS IAM id/secret keys for 'bas-gitlab-deploy-bas-style-kit-docs' user
# > AWS_ACCESS_KEY_ID: "[Sensetive]"
# > AWS_SECRET_ACCESS_KEY: "[Sensetive]"

# == Job Templates ==

.job_template_s3_sync: &job_template_s3_sync
  image:
    name: governmentpaas/awscli:latest
    entrypoint: [""]
  before_script:
    - "export CI_BUILD_REF_SHORT=`echo $CI_BUILD_REF | cut -c1-7`"
    - "export CI_BUILD_TAG_SHORT=`echo $CI_COMMIT_TAG | cut -c 2-`"
    - "export CDN_PROJECT_VERSION=$CI_BUILD_TAG_SHORT"

# == Global settings ==

stages:
  - build
  - package
  - deploy

image:
  name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs:2018-06-22-alpine
  entrypoint: [""]

variables:
  AWS_DEFAULT_REGION: eu-west-1
  PACKAGES_BUCKET: packages.data.bas.ac.uk
  PACKAGES_BUCKET_PATH: zips/apps
  S3_DEPLOYMENT_BUCKET_STAGE: style-kit-testing.web.bas.ac.uk
  S3_DEPLOYMENT_BUCKET_PROD: style-kit.web.bas.ac.uk
  APP_NAME: bas-style-kit-docs

# == Jobs ==

jekyll-build-develop:
  stage: build
  except:
    - master
    - tags
  variables:
    JEKYLL_ENV: develop
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

jekyll-build-staging:
  stage: build
  only:
    - master
  variables:
    JEKYLL_ENV: staging
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

jekyll-build-production:
  stage: build
  only:
    - tags
  variables:
    JEKYLL_ENV: production
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

package-site-content:
  stage: package
  image:
    name: kramos/alpine-zip:latest
    entrypoint: [""]
  before_script:
    - "export CI_BUILD_REF_SHORT=`echo $CI_BUILD_REF | cut -c1-7`"
    - "export DATETIME_INSTANT=`date --utc -Iseconds`"
    - "cd site/_site"
  script: "zip -r ../../$CI_BUILD_REF_SHORT-$DATETIME_INSTANT.zip *"
  artifacts:
    name: "$CI_BUILD_TOKEN-zip"
    paths:
      - "*.zip"
    expire_in: 1 day

s3-snapshot-staging:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - master
  script: "aws s3 cp $CI_BUILD_REF_SHORT-*.zip s3://$PACKAGES_BUCKET/$PACKAGES_BUCKET_PATH/$APP_NAME/snapshots/"


s3-snapshot-production:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - tags
  script: "aws s3 cp $CI_BUILD_REF_SHORT-*.zip s3://$PACKAGES_BUCKET/$PACKAGES_BUCKET_PATH/$APP_NAME/releases/$CDN_PROJECT_VERSION.zip"

s3-website-staging:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - master
  script: "aws s3 sync --delete site/_site s3://$S3_DEPLOYMENT_BUCKET_STAGE/"
  environment:
    name: staging
    url: https://style-kit-testing.web.bas.ac.uk

s3-website-production:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - tags
  script: "aws s3 sync --delete site/_site s3://$S3_DEPLOYMENT_BUCKET_PROD/"
  environment:
    name: production
    url: https://style-kit.web.bas.ac.uk
