---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs/settings/ci_cd -
#   see below

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - AWS IAM id/secret keys for 'bas-gitlab-deploy-bas-style-kit-docs' user
# > AWS_ACCESS_KEY_ID: "[Sensitive]"
# > AWS_SECRET_ACCESS_KEY: "[Sensitive]"

# == Global settings ==

stages:
  - build
  - deploy

image:
  name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs:2020-06-27-alpine
  entrypoint: [""]

variables:
  AWS_DEFAULT_REGION: eu-west-1
  S3_DEPLOYMENT_BUCKET_STAGE: style-kit-testing.web.bas.ac.uk
  S3_DEPLOYMENT_BUCKET_PROD: style-kit.web.bas.ac.uk
  APP_NAME: bas-style-kit-docs

# == Jobs ==

jekyll-build-develop:
  stage: build
  except:
    - master
    - tags
  variables:
    JEKYLL_ENV: develop
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

jekyll-build-staging:
  stage: build
  only:
    - master
  variables:
    JEKYLL_ENV: staging
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day

jekyll-build-production:
  stage: build
  only:
    - tags
  variables:
    JEKYLL_ENV: production
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 2 years

s3-website-staging:
  stage: deploy
  image:
    name: governmentpaas/awscli:latest
    entrypoint: [""]
  script: "aws s3 sync --delete site/_site s3://$S3_DEPLOYMENT_BUCKET_STAGE/"
  only:
    - master
  environment:
    name: staging
    url: https://style-kit-testing.web.bas.ac.uk

s3-website-production:
  stage: deploy
  image:
    name: governmentpaas/awscli:latest
    entrypoint: [""]
  script: "aws s3 sync --delete site/_site s3://$S3_DEPLOYMENT_BUCKET_PROD/"
  only:
    - tags
  environment:
    name: production
    url: https://style-kit.web.bas.ac.uk
