---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This configuration file uses some advanced YAML features (namely anchors) which may not be correctly displayed
#   by syntax highlighting
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs/settings/ci_cd -
#   see below

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensetive values are represented by "[Sensetive]"
#
# - AWS IAM id/secret keys for 'bas-gitlab-deploy-bas-style-kit-docs' user
# > AWS_ACCESS_KEY_ID: "[Sensetive]"
# > AWS_SECRET_ACCESS_KEY: "[Sensetive]"

# == Job Templates ==

.job_template_s3_sync: &job_template_s3_sync
  image:
    name: governmentpaas/awscli:latest
    entrypoint: [""]
  before_script:
    - "export CI_BUILD_REF_SHORT=`echo $CI_BUILD_REF | cut -c1-7`"
    - "export CI_BUILD_TAG_SHORT=`echo $CI_COMMIT_TAG | cut -c 2-`"
    - "export CDN_PROJECT_VERSION=$CI_BUILD_TAG_SHORT"

# == Global settings ==

stages:
  - build
  - package
  - deploy

image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs:2017-07-07-alpine

variables:
  AWS_DEFAULT_REGION: eu-west-1
  PACKAGES_BUCKET: bas-package-service-prod
  PACKAGES_BUCKET_PATH: zips/apps
  S3_DEPLOYMENT_BUCKET_STAGE: style-kit-testing.web.bas.ac.uk
  S3_DEPLOYMENT_BUCKET_PROD: style-kit.web.bas.ac.uk
  APP_NAME: bas-style-kit-docs

# == Jobs ==

jekyll-build-staging:
  stage: build
  only:
    - master
  variables:
    JEKYLL_ENV: staging
  before_script:
    - "cd site"
  script: "jekyll build"
  artifacts:
    name: "$CI_BUILD_TOKEN-content"
    paths:
      - site/_site
    expire_in: 1 day
