---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/bsk/bas-style-kit-docs:alpine-2016-12-26
    volumes:
      - ./site:/usr/src/app/site
    ports:
      - "9000:9000"
