---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit-docs:2018-09-21-alpine
    working_dir: /usr/src/app/site
    volumes:
      - ./site:/usr/src/app/site
    ports:
      - "9000:9000"
