# Vagrant configuration
  # Ruby syntax highlighting can be used for this file, as can regular ruby code.
  # Options using 'config' apply to all VMs

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Base box
  config.vm.box = "antarctica/trusty"
  config.vm.box_version = "~> 3.3"

  # Network adapters
    # DHCP is used to prevent clashes with other projects
    # If you need to share a vagrant VM with someone else it is recommended to use 'vagrant share',
    # rather than use public networking, as the security of development environments is often low.
  config.vm.network "private_network", type: "dhcp"  # Define Networking

  # Automatic hostname registration via the Landrush plugin
  config.landrush.enabled = true
  config.landrush.tld = 'v.m'

  # Shared folders
    # /vagrant is not used to ensure consistency across environments [development/staging/production]
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/usr/srv/apps/bas-style-kit-docs"

  # Virtual machine definitions
    # Options using 'node' apply to a single VM only
    # For BAS projects, the hostname **MUST** be the FQDN and comply with WSR-1, e.g. project-environment-purpose.v.m
    # the identifier **MUST** be the same as the hostname, without a domain, e.g. project-environment-purpose
  config.vm.define "bas-style-kit-docs-dev-node1" do |node|
    node.vm.hostname = "bas-style-kit-docs-dev-node1.v.m"

    # Provision all virtual machines using Ansible to get to a common 'foundation'
      # We also download all roles required fro this project using Ansible Galaxy
      #
      # Due to a bug in Vagrant this provisioner MUST be defined in the LAST virtual machine
      # Source: https://github.com/mitchellh/vagrant/issues/1784
    node.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.inventory_path = "../inventories"
      ansible.galaxy_role_file = "../galaxy.yml"
      ansible.galaxy_roles_path = "../roles"
      ansible.playbook = "vagrant-foundation.yml"
    end
  end
end
