# Build settings
#

markdown: kramdown
kramdown:
  auto_ids: false

theme: jekyll-theme-bas-style-kit

# Server settings
#

host: 0.0.0.0
port: 9000
encoding: UTF-8

# Site settings
#

# e.g. /foo
baseurl: ''

defaults:
  -
    scope:
      # an empty string here means all files in the project
      path: ""
    values:
      layout: "bas-style-kit/bsk--standard-page"
      bas_style_kit_jekyll_theme:
        feature_flags:
          page:
            toc: true

collections:
  start:
    output: true
    permalink: /:collection/:slug/
  core:
    output: true
    permalink: /:collection/:slug/
  components:
    output: true
    permalink: /:collection/:slug/
  interactivity:
    output: true
    permalink: /:collection/:slug/
  patterns:
    output: true
    permalink: /:collection/:slug/
  more:
    output: true
    permalink: /:collection/:slug/

# Theme settings
#

bas_style_kit_jekyll_theme:
  attributes:
    container: fixed
    head_title:
      # Used when `page.title` isn't set
      default: 'BAS Style Kit'
      appended: ' - BAS Style Kit'
    head_description: 'A collection of HTML, CSS, and JS components for developing web projects consistent with the BAS brand.'
    site_brand:
        text: 'BAS Style Kit'
        href: '/'
    site_development_phase: 'live'
    site_analytics:
      id: G-16B6W9T2B1
    site_styles:
        -
          href: 'https://cdn.web.bas.ac.uk/libs/font-awesome-pro/5.13.0/css/all.min.css'
          integrity: 'sha256-DjbUjEiuM4tczO997cVF1zbf91BC9OzycscGGk/ZKks='
          type: 'remote'
        -
          href: '/css/main.css'
          type: 'local'
