# Build settings
#

markdown: kramdown
kramdown:
  auto_ids: false

theme: jekyll-theme-bas-style-kit

# Server settings
#

host: 0.0.0.0
port: 9000
encoding: UTF-8

# Site settings
#

# e.g. /foo
baseurl: ''

defaults:
  -
    scope:
      # an empty string here means all files in the project
      path: ""
    values:
      layout: "bas-style-kit/bsk--standard-page"

collections:
  start:
    output: true
    permalink: /:collection/:slug/
  core:
    output: true
    permalink: /:collection/:slug/
  components:
    output: true
    permalink: /:collection/:slug/
  interactivity:
    output: true
    permalink: /:collection/:slug/
  examples:
    output: true
    permalink: /:collection/:slug/

# Theme settings
#

bas_style_kit_jekyll_theme:
  feature_flags:
    standard_footer:
      divider: false
  attributes:
    container: fixed
    head_title:
      # Used when `page.title` isn't set
      default: 'BAS Style Kit'
      appended: ' - BAS Style Kit'
    head_description: 'A collection of HTML, CSS, and JS components for developing web projects consistent with the BAS brand.'
    site_brand:
        text: 'BAS Style Kit'
        href: '/'
    site_development_phase: 'experimental'
    site_analytics:
      id: UA-64130716-27
    site_styles:
        -
          href: '/css/main.css'
          type: 'local'
    site_footer:
      legal_policies:
        copyright_href: '/legal/copyright'
        cookies_href: '/legal/cookies'
        privacy_href: '/legal/privacy'
