# Build settings
#

markdown: kramdown
theme: jekyll-theme-bas-style-kit

# Server settings
#

host: 0.0.0.0
port: 9000
encoding: UTF-8

# Site settings
#

# e.g. /foo
baseurl: ''

defaults:
  -
    scope:
      # an empty string here means all files in the project
      path: ""
    values:
      layout: "bas-style-kit/bsk--standard-page"

# Theme settings
#

bas_style_kit_jekyll_theme:
  attributes:
    container: fixed
    head_title:
      # Used when `page.title` isn't set
      default: 'BAS Style Kit'
    head_description: 'Documentation for the BAS Style Kit'
    site_brand:
        text: 'BAS Style Kit'
        href: '/'
    site_development_phase: 'experimental'
