---
# Install additional Ruby Gems for Jekyll plugins

# In preparation for Ansible 2.0
- name: install additional ruby gems for jekyll plugins
  bundler:
    chdir="{{ app_project_directory }}/site"
    state=present
  become: no
