---
# Setup infrastructure and application for development environment

- name: setup development nodes
  hosts: project--bas-style-kit-docs:&env--dev-local
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  roles:
    - bas-ansible-roles-collection.system-core
    - bas-ansible-roles-collection.jekyll3
  tasks:
    - include: tasks/shims/jekyll/configure-firewall.yml
    - include: tasks/shims/ruby/install-bundler.yml
    - include: tasks/ruby/install-ruby-gems.yml
  handlers:
    - name: Restart Firewall - Ubuntu
      ufw: state=reloaded
